const BlogEleven = () => {
  return (
    <div className="text-left flex flex-col py-8 space-y-12 max-w-[1000px] mx-auto px-4 ">
      <p className="text-lg sm:text-xl">
        Imagine a potential customer who visits the online stores, browses the
        product, and adds items to the cart but before they complete the
        purchase, they pause and leave your website and disappear into the vast
        world of the internet. In the world of traditional advertising, it might
        have been the end of the story but in the world of digital marketing,
        any missed conversion presents a chance to reignite the interest and
        lead those prospects back into the sales funnel. That is why retargeting
        is the process that comes in to recapture leads that have been
        previously engaged with the brand and left in the middle. One can know
        about them from a web designing services provider as they have the tools
        and techniques to tell that.
      </p>

      <div className="space-y-4">
        <h1 className="text-xl sm:text-2xl font-semibold">
          What is Retargeting?
        </h1>
        <p className="text-lg sm:text-xl">
          Retargeting helps in the process of getting the users back to the
          website. It is beyond re-engaging first time visitors and this
          approach lets one connect with the warm leads or someone who has shown
          interest in the website. It includes those users who previously
          explored the web pages or took specific actions like downloading
          whitepaper or adding items to the cart. Let us learn about the factors
          that can help with retargeting the audience.
        </p>
      </div>

      <div className="space-y-4">
        <h1 className="text-xl sm:text-2xl font-semibold">
          Browsing Behaviour
        </h1>
        <p className="text-lg sm:text-xl">
          Not every time a user leaves your website because you don’t have
          something to offer but most of the time it happens that they are just
          comparing prices, gathering information, or learning about different
          models.
        </p>

        <div className="space-y-3 py-4">
          <h1 className="text-xl sm:text-2xl font-semibold">User Experience</h1>
          <p className="text-lg sm:text-xl">
            It takes a second whether the visitor stays on the page or exits, if
            the website is slow the customers probably will leave and it will
            negatively affect the website.
          </p>
        </div>
        <div className="space-y-3 py-4">
          <h1 className="text-xl sm:text-2xl font-semibold">Lack of Trust</h1>
          <p className="text-lg sm:text-xl">
            Almost every customer requires that they can trust the brand and the
            product or service beyond that. Customers who view the website for
            the first time may be likely to leave if they lack signals of trust.
          </p>
        </div>
        <div className="space-y-3 py-4">
          <h1 className="text-xl sm:text-2xl font-semibold">
            How does Retargeting Work?
          </h1>
          <p className="text-lg sm:text-xl">
            Retargeting is often covered up with the help of cookies which are
            tiny pieces of data stored by the web browsers to get the visitor
            information. Cookies allow the third party to monitor a user's
            online activities, including the website they visit and products
            they view or purchase. Although the identity remains anonymous, the
            IP address retains and allows the cookies to create a profile of
            their interests and online behavior.
          </p>
          <p className="text-lg sm:text-xl">
            The data collected is then shared with third-party retargeting
            platforms such as Google, Instagram, and others to deliver tailored
            advertisements with the user's recent interests or browsing
            activity. If we see an example one can see the relevant ads about
            the search they had just made.
          </p>
          <h1 className="text-xl sm:text-2xl font-semibold">
            There are two types of cookies.
          </h1>
          <ul className="list-none sm:list-disc space-y-4 py-4 pl-8">
            <li className="text-lg sm:text-xl list">
              <span className="text-xl sm:text-2xl font-semibold">
                First-Party Cookies{": "}
              </span>
              These cookies are generated by the website a user visits. It is
              allowed that the site can identify user devices and retain this
              information to enhance the browsing experience such as having
              strong items in the cart or remembering the login status.
            </li>
            <li className="text-lg sm:text-xl">
              <span className="text-xl sm:text-2xl font-semibold">
                Third-Party Cookies{": "}
              </span>
              These cookies are usually deposited into a user's browser by a
              website that is different from the one that is presently visiting.
              These cookies can only monitor visitors when they move between
              websites and allow the collection of data based on user
              preferences, behaviors, and interests.
            </li>
          </ul>
        </div>
      </div>
      <div className="space-y-3 py-4">
        <h1 className="text-xl sm:text-3xl font-semibold">Conclusion</h1>
        <p className="text-lg sm:text-xl">
          Retargeting is an important aspect as it may allow one to find the
          valuable customers that they have lost and to do so one needs to take
          the digital marketing services from a web development services
          provider as they generally have the solution for that. The best
          digital marketing services provider is Maya Web Tech as they have all
          the different tools and techniques to get one with success.
        </p>
      </div>
    </div>
  );
};

export default BlogEleven;
